registry_path = "./untracked/registry.json"
remote_path = "gdrive:backups/"

[databases.fuel_log]
source = "./untracked/fuel/backend/fuel_log.db"
stage = "./untracked/stage/fuel_log/"

[databases.pay_log]
source = "./untracked/pay/backend/pay_log.db"
stage = "./untracked/stage/pay_log/"
